(custom-set-variables
  ;; custom-set-variables was added by Custom.
  ;; If you edit it by hand, you could mess it up, so be careful.
  ;; Your init file should contain only one such instance.
  ;; If there is more than one, they won't work right.
 '(Info-additional-directory-list (quote ("/opt/local/share/info")))
 '(ansi-color-for-comint-mode t)
 '(aquamacs-additional-fontsets nil t)
 '(aquamacs-autoface-mode nil)
 '(aquamacs-customization-version-id 208 t)
 '(aquamacs-tool-bar-user-customization nil t)
 '(backup-directory-alist (quote (("." . "~/.backups"))))
 '(blink-cursor-mode t)
 '(bookmark-save-flag 0)
 '(compilation-scroll-output t)
 '(cursor-type (quote box) t)
 '(delete-selection-mode t)
 '(display-time-mode t)
 '(erc-autojoin-channels-alist (quote (("freenode.net" "#steamcannon" "#torquebox" "#stormgrind") ("redhat.com" "#emacs" "#oddteam"))))
 '(erc-autojoin-mode t)
 '(erc-hide-list (quote ("KICK" "NICK" "MODE")))
 '(erc-interpret-mirc-color t)
 '(erc-mode-line-format "%s %a. %n on %t (%m,%l)")
 '(erc-modules (quote (autojoin button completion fill irccontrols keep-place list log match menu move-to-prompt netsplit networks noncommands readonly ring stamp track highlight-nicknames)))
 '(erc-nick "jc3")
 '(erc-pal-highlight-type (quote all))
 '(erc-pals (quote ("bobmcw" "mgoldmann" "bbrowning" "tcrawley" "lanceball")))
 '(erc-server "irc.freenode.net")
 '(erc-track-switch-direction (quote importance))
 '(exec-path (quote ("/opt/local/bin" "/opt/local/sbin" "~/local/torquebox/jruby/bin" "/usr/bin" "/bin" "/usr/sbin" "/sbin")))
 '(gnus-init-file "~/.emacs.d/.gnus.el")
 '(gnus-total-expirable-newsgroups ".")
 '(grep-command "grep -nHi -e ")
 '(grep-find-ignored-directories (quote ("SCCS" "RCS" "CVS" "MCVS" ".svn" ".git" ".hg" ".bzr" "_MTN" "_darcs" "{arch}" "target")))
 '(ido-mode (quote both) nil (ido))
 '(indent-tabs-mode nil)
 '(jtags-etags-command "find `pwd` | grep -v target | egrep \"\\.(rb|java)$\" | /usr/bin/etags --declarations --members -o %f -")
 '(kill-whole-line t)
 '(ldap-host-parameters-alist (quote (("ldap.corp.redhat.com" base "ou=users,dc=redhat,dc=com" scope subtree deref always))))
 '(ldap-ldapsearch-args (quote ("-LLL" "-tt" "-x")))
 '(nnmail-expiry-wait 14)
 '(ns-alternate-modifier (quote super))
 '(ns-command-modifier (quote meta))
 '(ns-tool-bar-display-mode (quote both) t)
 '(ns-tool-bar-size-mode (quote regular) t)
 '(nxml-slash-auto-complete-flag t)
 '(show-paren-mode t)
 '(smtpmail-smtp-server "smtp.corp.redhat.com")
 '(split-width-threshold nil)
 '(tab-width 4)
 '(uniquify-buffer-name-style (quote forward) nil (uniquify))
 '(visual-line-mode nil t)
 '(w3m-fill-column 100)
 '(x-select-enable-clipboard t))
(custom-set-faces
  ;; custom-set-faces was added by Custom.
  ;; If you edit it by hand, you could mess it up, so be careful.
  ;; Your init file should contain only one such instance.
  ;; If there is more than one, they won't work right.
 )
