(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(ansi-color-faces-vector [default bold shadow italic underline bold bold-italic bold])
 '(ansi-color-names-vector ["#242424" "#e5786d" "#95e454" "#cae682" "#8ac6f2" "#333366" "#ccaa8f" "#f6f3e8"])
 '(auto-save-file-name-transforms (quote (("\\`/[^/]*:\\([^/]*/\\)*\\([^/]*\\)\\'" "/var/folders/Gf/GfQtOY0rGnK+iehSsqpuhU+++TI/-Tmp-/\\2" t) (".*" "~/.backups/" t))))
 '(background-color "#fcf4dc")
 '(background-mode light)
 '(blink-cursor-mode t)
 '(bookmark-save-flag 0)
 '(comint-scroll-show-maximum-output nil)
 '(compilation-scroll-output t)
 '(compilation-skip-threshold 2)
 '(cursor-color "#52676f")
 '(custom-enabled-themes (quote (sanityinc-tomorrow-bright)))
 '(custom-safe-themes (quote ("82d2cac368ccdec2fcc7573f24c3f79654b78bf133096f9b40c20d97ec1d8016" "628278136f88aa1a151bb2d6c8a86bf2b7631fbea5f0f76cba2a0079cd910f7d" "1e7e097ec8cb1f8c3a912d7e1e0331caeed49fef6cff220be63bd2a6ba4cc365" "fc5fcb6f1f1c1bc01305694c59a1a861b008c534cae8d0e48e4d5e81ad718bc6" "06f0b439b62164c6f8f84fdda32b62fb50b6d00e8b01c2208e55543a6337433a" "bb08c73af94ee74453c90422485b29e5643b73b05e8de029a6909af6a3fb3f58" "1b8d67b43ff1723960eb5e0cba512a2c7a2ad544ddb2533a90101fd1852b426e" "b7553781f4a831d5af6545f7a5967eb002c8daeee688c5cbf33bf27936ec18b3" default)))
 '(delete-selection-mode t)
 '(erc-auto-discard-away nil)
 '(erc-autoaway-idle-seconds 7200)
 '(erc-autoaway-mode t)
 '(erc-autojoin-channels-alist (quote (("freenode.net" "#hornetq" "#asjs" "#infinispan" "#immutant" "#clojure" "#jruby" "#jboss-dev" "#jboss-as7" "#torquebox" "#boxgrinder" "#leiningen") ("redhat.com" "#wfk" "#projectodd"))))
 '(erc-autojoin-mode t)
 '(erc-away-nickname "jcrossley3-away")
 '(erc-hide-list (quote ("KICK" "PART" "QUIT" "MODE")))
 '(erc-hl-nicks-skip-faces (quote ("erc-fool-face")))
 '(erc-insert-timestamp-function (quote erc-insert-timestamp-right))
 '(erc-interpret-mirc-color t)
 '(erc-mode-line-format "%s %a. %n on %t (%m,%l)")
 '(erc-modules (quote (autoaway autojoin button completion fill irccontrols keep-place list log match menu move-to-prompt netsplit networks noncommands readonly ring stamp track hl-nicks)))
 '(erc-nick "jcrossley3")
 '(erc-pal-highlight-type (quote all))
 '(erc-server "irc.freenode.net")
 '(erc-track-exclude-server-buffer t)
 '(erc-track-exclude-types (quote ("JOIN" "NICK" "PART" "QUIT" "333" "353")))
 '(erc-track-showcount t)
 '(erc-track-switch-direction (quote importance))
 '(fci-rule-color "#383838")
 '(foreground-color "#52676f")
 '(global-hl-line-mode t)
 '(gnus-init-file "~/.emacs.d/.gnus.el")
 '(grep-find-ignored-directories (quote ("SCCS" "RCS" "CVS" "MCVS" ".svn" ".git" ".hg" ".bzr" "_MTN" "_darcs" "{arch}" "target")))
 '(jtags-etags-command "find `pwd` | grep -v target | egrep \"\\.(rb|java)$\" | /usr/bin/etags --declarations --members -o %f -")
 '(kill-whole-line t)
 '(ldap-host-parameters-alist (quote (("ldap.corp.redhat.com"))))
 '(mm-discouraged-alternatives (quote ("text/html" "multipart/mixed")))
 '(ns-alternate-modifier (quote super))
 '(ns-command-modifier (quote meta))
 '(nxml-slash-auto-complete-flag t)
 '(org-babel-load-languages (quote ((ruby . t) (clojure . t) (emacs-lisp . t))))
 '(org-hide-leading-stars t)
 '(org-src-fontify-natively t)
 '(visible-bell t))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(cursor ((t (:background "Orange"))))
 '(erc-pal-face ((t (:foreground "Magenta"))))
 '(erc-timestamp-face ((t (:foreground "green"))))
 '(header-line ((t (:inherit mode-line :background "#303030" :foreground "Green" :box nil))))
 '(hl-line ((t (:weight extra-bold))))
 '(hl-line-face ((t nil)) t)
 '(magit-item-highlight ((t (:weight extra-bold)))))
