(deftheme zenburn-extra
  "Created 2013-03-16.")

(custom-theme-set-faces
 'zenburn-extra
 '(cursor ((t (:background "orange" :foreground "#dcdccc"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((t (:family "Sans Serif"))))
 '(escape-glyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:foreground "#f0dfaf"))))
 '(highlight ((t (:background "#2b2b2b"))))
 '(region ((t (:background "darkgreen"))))
 '(shadow ((((class color grayscale) (min-colors 88) (background light)) (:foreground "grey50")) (((class color grayscale) (min-colors 88) (background dark)) (:foreground "grey70")) (((class color) (min-colors 8) (background light)) (:foreground "green")) (((class color) (min-colors 8) (background dark)) (:foreground "yellow"))))
 '(secondary-selection ((t (:background "#5f5f5f"))))
 '(trailing-whitespace ((t (:background "#cc9393"))))
 '(font-lock-builtin-face ((t (:foreground "#8cd0d3"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#7f9f7f" :inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:foreground "#7f9f7f"))))
 '(font-lock-constant-face ((t (:foreground "#bfebbf"))))
 '(font-lock-doc-face ((t (:inherit font-lock-string-face :foreground "#8fb28f"))))
 '(font-lock-function-name-face ((t (:foreground "#8cd0d3"))))
 '(font-lock-keyword-face ((t (:weight bold :foreground "#f0dfaf"))))
 '(font-lock-negation-char-face ((t (:foreground "#dcdccc"))))
 '(font-lock-preprocessor-face ((t (:foreground "#8cd0d3" :inherit (font-lock-builtin-face)))))
 '(font-lock-regexp-grouping-backslash ((t (:inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "#cc9393"))))
 '(font-lock-type-face ((t (:foreground "#8cd0d3"))))
 '(font-lock-variable-name-face ((t (:foreground "#dfaf8f"))))
 '(font-lock-warning-face ((t (:weight bold :underline t :foreground "#e0cf9f" :inherit (error)))))
 '(button ((t (:underline t :inherit (link)))))
 '(link ((t (:weight bold :underline t :foreground "#f0dfaf"))))
 '(link-visited ((t (:weight normal :underline t :foreground "#d0bf8f" :inherit (link)))))
 '(fringe ((t (:foreground "#dcdccc" :background "#4f4f4f"))))
 '(header-line ((t (:box (:line-width -1 :color nil :style released-button) :foreground "#f0dfaf" :background "#2b2b2b" :inherit (mode-line)))))
 '(tooltip ((((class color)) (:inherit (variable-pitch) :foreground "black" :background "lightyellow")) (t (:inherit (variable-pitch)))))
 '(mode-line ((t (:background "#2b2b2b" :foreground "#8fb28f" :box (:line-width -1 :style released-button)))))
 '(mode-line-buffer-id ((t (:weight bold :foreground "#f0dfaf"))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((((class color) (min-colors 88)) (:box (:line-width 2 :color "grey40" :style released-button))) (t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:weight light :box (:line-width -1 :color nil :style released-button) :foreground "#5f7f5f" :background "#383838" :inherit (mode-line)))))
 '(isearch ((t (:foreground "#f0dfaf" :background "#2b2b2b"))))
 '(isearch-fail ((t (:background "#8c5353" :foreground "#dcdccc"))))
 '(lazy-highlight ((t (:background "#5f5f5f" :foreground "#f0dfaf"))))
 '(match ((t (:weight bold :foreground "#dfaf8f" :background "#2b2b2b"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch)))))
 '(hl-line ((t (:background "black" :weight extra-bold))))
 '(erc-prompt-face ((t (:background "gray" :foreground "#8c5353" :weight bold))))
 '(erc-default-face ((t (:foreground "#dcdccc"))))
 '(default ((t (:inherit nil :stipple nil :background "#3f3f3f" :foreground "#dcdccc" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 150 :width normal :foundry "apple" :family "Monaco")))))

(provide-theme 'zenburn-extra)
